export enum Tables {
  CHAT_CONVERSATIONS = "chat_conversations",
  COMPARISON_CONVERSATIONS = "comparison_conversations",
  CHAT_MESSAGES = "chat_messages",
  CHAT_MESSAGE_STATS = "chat_message_stats",
  COMPARISON_PROMPTS = "comparison_prompts",
  COMPARISON_OUTPUTS = "comparison_outputs",
  COMPARISON_OUTPUT_STATS = "comparison_output_stats",
  USAGE_PER_MODEL = "usage_per_model",
  USAGE_USER_MODEL = "usage_user_model",
  USAGE_CONVERSATION = "usage_conversation",
  PROJECTS = "projects",
  DOCUMENTS = "documents",
  DOCUMENT_CHUNKS = "document_chunks",
  USED_DOCUMENTS = "used_documents",
  PROJECT_CONVERSATIONS = "project_conversations",
  PROJECT_MESSAGES = "project_messages",
  PROJECT_MESSAGE_STATS = "project_message_stats",
}
